revert fluff change

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -161,200 +161,160 @@ jobs:
         uses: ./.github/actions/setup-builder
       - name: Verify that benchmark queries return expected results
         run: |
-          cargo test --profile ci --package ballista-benchmarks --profile release-nonlto --features=ci --locked -- --test-threads=1 
+          cargo test --profile ci --package ballista-benchmarks --features=ci --locked -- --test-threads=1 
 
-  vendor:
-    name: Verify Vendored Code
+  lint:
+    name: Lint
     runs-on: ubuntu-latest
     container:
       image: amd64/rust
     steps:
       - uses: actions/checkout@v4
-      - name: Setup Rust toolchain
-        uses: ./.github/actions/setup-builder
-        with:
-          rust-version: stable
-      - name: Run gen
-        run: ./regen.sh
-        working-directory: ./datafusion/proto
-      - name: Verify workspace clean (if this fails, run ./datafusion/proto/regen.sh and check in results)
-        run: git diff --exit-code
-
-  check-fmt:
-    name: Check cargo fmt
-    runs-on: ubuntu-latest
-    container:
-      image: amd64/rust
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup Rust toolchain
-        uses: ./.github/actions/setup-builder
-        with:
-          rust-version: stable
-      - name: Run
+      - name: Setup toolchain
         run: |
-          echo '' > datafusion/proto/src/generated/datafusion.rs
-          ci/scripts/rust_fmt.sh
-
-  # Coverage job disabled due to
-  # https://github.com/apache/datafusion/issues/3678
-
-  # coverage:
-  #   name: coverage
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: true
-  #     - name: Install protobuf compiler
-  #       shell: bash
-  #       run: |
-  #         mkdir -p $HOME/d/protoc
-  #         cd $HOME/d/protoc
-  #         export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
-  #         curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
-  #         unzip $PROTO_ZIP
-  #         export PATH=$PATH:$HOME/d/protoc/bin
-  #         protoc --version
-  #     - name: Setup Rust toolchain
-  #       run: |
-  #         rustup toolchain install stable
-  #         rustup default stable
-  #         rustup component add rustfmt clippy
-  #     - name: Cache Cargo
-  #       uses: actions/cache@v4
-  #       with:
-  #         path: /home/runner/.cargo
-  #         # this key is not equal because the user is different than on a container (runner vs github)
-  #         key: cargo-coverage-cache3-
-  #     - name: Run coverage
-  #       run: |
-  #         export PATH=$PATH:$HOME/d/protoc/bin
-  #         rustup toolchain install stable
-  #         rustup default stable
-  #         cargo install --version 0.20.1 cargo-tarpaulin
-  #         cargo tarpaulin --all --out Xml
-  #     - name: Report coverage
-  #       continue-on-error: true
-  #       run: bash <(curl -s https://codecov.io/bash)
+          rustup toolchain install stable
+          rustup default stable
+          rustup component add rustfmt
+      - name: Run
+        run: ci/scripts/rust_fmt.sh
+        env:
+          CARGO_HOME: "/github/home/.cargo"
+          CARGO_TARGET_DIR: "/github/home/target"
 
   clippy:
-    name: clippy
-    needs: linux-build-lib
+    name: Clippy
+    needs: [linux-build-lib]
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch: [amd64]
+        rust: [stable]
     container:
-      image: amd64/rust
+      image: ${{ matrix.arch }}/rust
+      env:
+        # Disable full debug symbol generation to speed up CI build and keep memory down
+        # "1" means line tables only, which is useful for panic tracebacks.
+        RUSTFLAGS: "-C debuginfo=1"
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: true
-          fetch-depth: 1
+      - name: Cache Cargo
+        uses: actions/cache@v4
+        with:
+          path: /github/home/.cargo
+          # this key equals the ones on `linux-build-lib` for re-use
+          key: cargo-cache-
+      - name: Cache Rust dependencies
+        uses: actions/cache@v4
+        with:
+          path: /github/home/target
+          # this key equals the ones on `linux-build-lib` for re-use
+          key: ${{ runner.os }}-${{ matrix.arch }}-target-cache-${{ matrix.rust }}
       - name: Setup Rust toolchain
         uses: ./.github/actions/setup-builder
         with:
-          rust-version: stable
+          rust-version: ${{ matrix.rust }}
       - name: Install Clippy
-        run: rustup component add clippy
+        run: |
+          rustup component add clippy
       - name: Run clippy
         run: ci/scripts/rust_clippy.sh
+        env:
+          CARGO_HOME: "/github/home/.cargo"
+          CARGO_TARGET_DIR: "/github/home/target"
 
   cargo-toml-formatting-checks:
-    name: check Cargo.toml formatting
-    needs: linux-build-lib
+    name: Check Cargo.toml formatting
+    needs: [linux-build-lib]
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch: [amd64]
+        rust: [stable]
     container:
-      image: amd64/rust
+      image: ${{ matrix.arch }}/rust
+      env:
+        # Disable full debug symbol generation to speed up CI build and keep memory down
+        # "1" means line tables only, which is useful for panic tracebacks.
+        RUSTFLAGS: "-C debuginfo=1"
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: true
-          fetch-depth: 1
+      - name: Cache Cargo
+        uses: actions/cache@v4
+        with:
+          path: /github/home/.cargo
+          # this key equals the ones on `linux-build-lib` for re-use
+          key: cargo-cache-
+      - name: Cache Rust dependencies
+        uses: actions/cache@v4
+        with:
+          path: /github/home/target
+          # this key equals the ones on `linux-build-lib` for re-use
+          key: ${{ runner.os }}-${{ matrix.arch }}-target-cache-${{ matrix.rust }}
       - name: Setup Rust toolchain
         uses: ./.github/actions/setup-builder
         with:
-          rust-version: stable
-      - name: Install taplo
-        run: cargo +stable install taplo-cli --version ^0.9 --locked
-      # if you encounter an error, try running 'taplo format' to fix the formatting automatically.
+          rust-version: ${{ matrix.rust }}
+      - name: Install cargo-tomlfmt
+        run: |
+          which cargo-tomlfmt || cargo install cargo-tomlfmt
+        env:
+          CARGO_HOME: "/github/home/.cargo"
+          CARGO_TARGET_DIR: "/github/home/target"
       - name: Check Cargo.toml formatting
-        run: taplo format --check
+        run: |
+          # if you encounter error, try rerun the command below, finally run 'git diff' to
+          # check which Cargo.toml introduces formatting violation
+          #
+          # ignore ./Cargo.toml because putting workspaces in multi-line lists make it easy to read
+          ci/scripts/rust_toml_fmt.sh
+          if test -f "./Cargo.toml.bak"; then
+              echo "cargo tomlfmt found format violations"
+              exit 1
+          fi
+        env:
+          CARGO_HOME: "/github/home/.cargo"
+          CARGO_TARGET_DIR: "/github/home/target"
+# Coverage job was failing. https://github.com/apache/arrow-datafusion/issues/590 tracks re-instating it
 
-  config-docs-check:
-    name: check configs.md and ***_functions.md is up-to-date
-    needs: linux-build-lib
-    runs-on: ubuntu-latest
-    container:
-      image: amd64/rust
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: true
-          fetch-depth: 1
-      - name: Setup Rust toolchain
-        uses: ./.github/actions/setup-builder
-        with:
-          rust-version: stable
-      - uses: actions/setup-node@v4
-        with:
-          node-version: "20"
-      - name: Check if configs.md has been modified
-        run: |
-          # If you encounter an error, run './dev/update_config_docs.sh' and commit
-          ./dev/update_config_docs.sh
-          git diff --exit-code
-      - name: Check if any of the ***_functions.md has been modified
-        run: |
-          # If you encounter an error, run './dev/update_function_docs.sh' and commit
-          ./dev/update_function_docs.sh
-          git diff --exit-code
-      - name: Check if runtime_configs.md has been modified
-        run: |
-          # If you encounter an error, run './dev/update_runtime_config_docs.sh' and commit
-          ./dev/update_runtime_config_docs.sh
-          git diff --exit-code
+# coverage:
+#   name: Coverage
+#   runs-on: ubuntu-latest
+#   strategy:
+#     matrix:
+#       arch: [amd64]
+#       rust: [stable]
+#   steps:
+#     - uses: actions/checkout@v4
+#       with:
+#         submodules: true
+#     - name: Cache Cargo
+#       uses: actions/cache@v4
+#       with:
+#         path: /home/runner/.cargo
+#         # this key is not equal because the user is different than on a container (runner vs github)
+#         key: cargo-coverage-cache-
+#     - name: Cache Rust dependencies
+#       uses: actions/cache@v4
+#       with:
+#         path: /home/runner/target
+#         # this key is not equal because coverage uses different compilation flags.
+#         key: ${{ runner.os }}-${{ matrix.arch }}-target-coverage-cache-${{ matrix.rust }}-
+#     - name: Run coverage
+#       run: |
+#         export ARROW_TEST_DATA=$(pwd)/testing/data
+#         export PARQUET_TEST_DATA=$(pwd)/parquet-testing/data
 
-  # Verify MSRV for the crates which are directly used by other projects:
-  # - datafusion
-  # - datafusion-substrait
-  # - datafusion-proto
-  # - datafusion-cli
-  msrv:
-    name: Verify MSRV (Min Supported Rust Version)
-    runs-on: ubuntu-latest
-    container:
-      image: amd64/rust
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup Rust toolchain
-        uses: ./.github/actions/setup-builder
-      - name: Install cargo-msrv
-        run: cargo install cargo-msrv
-      - name: Check datafusion
-        working-directory: datafusion/core
-        run: |
-          # If you encounter an error with any of the commands below it means
-          # your code or some crate in the dependency tree has a higher MSRV
-          # (Min Supported Rust Version) than the one specified in the
-          # `rust-version` key of `Cargo.toml`.
-          #
-          # To reproduce:
-          # 1. Install the version of Rust that is failing. Example:
-          #    rustup install 1.80.1
-          # 2. Run the command that failed with that version. Example:
-          #    cargo +1.80.1 check -p datafusion
-          #
-          # To resolve, either:
-          # 1. Change your code to use older Rust features,
-          # 2. Revert dependency update
-          # 3. Update the MSRV version in `Cargo.toml`
-          #
-          # Please see the DataFusion Rust Version Compatibility Policy before
-          # updating Cargo.toml. You may have to update the code instead.
-          # https://github.com/apache/datafusion/blob/main/README.md#rust-version-compatibility-policy
-          cargo msrv --output-format json --log-target stdout verify
-      - name: Check datafusion-substrait
-        working-directory: datafusion/substrait
-        run: cargo msrv --output-format json --log-target stdout verify
-      - name: Check datafusion-proto
-        working-directory: datafusion/proto
-        run: cargo msrv --output-format json --log-target stdout verify
+#         # 2020-11-15: There is a cargo-tarpaulin regression in 0.17.0
+#         # see https://github.com/xd009642/tarpaulin/issues/618
+#         cargo install --version 0.16.0 cargo-tarpaulin
+#         cargo tarpaulin --out Xml
+#       env:
+#         CARGO_HOME: "/home/runner/.cargo"
+#         CARGO_TARGET_DIR: "/home/runner/target"
+#     - name: Report coverage
+#       continue-on-error: true
+#       run: bash <(curl -s https://codecov.io/bash)
